import { Brain, AlertCircle, ChevronDown, ChevronUp } from 'lucide-react'
import { useState, useMemo } from 'react'

export default function InsightPanel({ insight, error }) {
  const [expanded, setExpanded] = useState(false)

  const isLong = useMemo(() => insight?.length > 600, [insight])

  if (error) {
    return (
      <div className="rounded-2xl border border-red-200 bg-red-50 p-5 shadow-[--shadow-card] animate-fade-in-up">
        <div className="flex items-start gap-3">
          <div className="p-1.5 rounded-lg bg-red-100">
            <AlertCircle className="h-4 w-4 text-red-500" />
          </div>
          <div>
            <h3 className="font-semibold text-red-700 mb-1">Analysis Error</h3>
            <p className="text-sm text-red-600">{error}</p>
          </div>
        </div>
      </div>
    )
  }

  if (!insight) {
    return <div className="h-36 rounded-2xl skeleton-pearl" />
  }

  const formatInsight = (text) =>
    text.split('\n').map((line, i) => {
      const t = line.trim()
      if (!t) return <br key={i} />

      // **Bold headers**
      if (t.startsWith('**') && t.endsWith('**')) {
        return (
          <p key={i} className="font-semibold text-text-primary mt-3 mb-1 first:mt-0">
            {t.slice(2, -2)}
          </p>
        )
      }

      // ## Markdown headers
      if (t.startsWith('## ')) {
        return (
          <p key={i} className="font-semibold text-text-primary mt-3 mb-1 first:mt-0">
            {t.slice(3)}
          </p>
        )
      }

      // Bullet points
      if (t.startsWith('- ') || t.startsWith('* ')) {
        return (
          <div key={i} className="flex gap-2 pl-1">
            <span className="mt-2 w-1 h-1 rounded-full bg-accent-pearl shrink-0" />
            <p className="text-sm text-text-secondary leading-relaxed">
              {t.slice(2)}
            </p>
          </div>
        )
      }

      return (
        <p key={i} className="text-sm text-text-secondary leading-relaxed">
          {t}
        </p>
      )
    })

  return (
    <div className="rounded-2xl border border-border-subtle bg-card shadow-[--shadow-card] overflow-hidden animate-fade-in-up stagger-3">
      <div className="border-l-4 border-accent-blue p-5">
        <div className="flex items-start gap-3">
          <div className="p-1.5 rounded-lg bg-accent-blue/10">
            <Brain className="h-4 w-4 text-accent-blue" />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="font-semibold text-text-primary tracking-tight mb-3">
              AI Clinical Insight
            </h3>

            <div
              className={`space-y-0.5 ${isLong && !expanded ? 'max-h-48 overflow-hidden relative' : ''}`}
            >
              {formatInsight(insight)}
              {isLong && !expanded && (
                <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-card to-transparent" />
              )}
            </div>

            {isLong && (
              <button
                onClick={() => setExpanded(!expanded)}
                className="mt-3 flex items-center gap-1 text-xs font-medium text-accent-blue hover:text-accent-blue/80 transition-colors cursor-pointer"
              >
                {expanded ? (
                  <>
                    Show less <ChevronUp className="h-3 w-3" />
                  </>
                ) : (
                  <>
                    Read more <ChevronDown className="h-3 w-3" />
                  </>
                )}
              </button>
            )}
          </div>
        </div>

        <p className="mt-4 pt-3 border-t border-border-subtle text-xs text-text-muted italic">
          Generated by Gemini 2.5 Flash &mdash; For research purposes only. Not
          intended for clinical diagnosis.
        </p>
      </div>
    </div>
  )
}
